fix: remove unused function
src/views/home/HomeView.vue:100:10 - error TS6133: 'marketCurrency' is declared but its value is never read.

100 function marketCurrency(market: string): string {